# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      OPENMP_EXPECTED: "True"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

      # babel 2.0 is known to break on Windows:
      # https://github.com/python-babel/babel/issues/174
      CONDA_DEPENDENCIES: "numpy Cython sphinx-astropy pytest babel!=2.0 setuptools pytest-cov"
      PIP_DEPENDENCIES: "codecov"

  matrix:
      - PYTHON_VERSION: "3.5"
      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "3.7"

platform:
    -x64

install:

    # Set up ci-helpers
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Some of the tests use git commands that require a user to be configured
    - git config --global user.name "A U Thor"
    - git config --global user.email "author@example.com"

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
  # Specify basetemp explicitly otherwise some of the filenames exceed
  # 260 characters when fetch_build_eggs runs.
  - "%CMD_IN_ENV% py.test --cov --basetemp=\\pytest-tmp astropy_helpers"
  - "%CMD_IN_ENV% codecov"
