# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

      
      # List runtime dependencies for the package that are available as conda
      # packages here.
      CONDA_DEPENDENCIES: ""
      
      # List other runtime dependencies for the package that are available as
      # pip packages here.
      PIP_DEPENDENCIES: ""

      # Conda packages for affiliated packages are hosted in channel
      # "astropy" while builds for astropy LTS with recent numpy versions
      # are in astropy-ci-extras. If your package uses either of these,
      # add the channels to CONDA_CHANNELS along with any other channels
      # you want to use.
      CONDA_CHANNELS: "astropy-ci-extras astropy"

  matrix:
      # We test Python 3.7 for Python 3 support.
      - PYTHON_VERSION: "3.7"
        ASTROPY_VERSION: "stable"
        NUMPY_VERSION: "stable"

platform:
    -x64

install:
    - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"
