# Autogenerated by Astropy-affiliated package hoki's setup.py on 2020-04-02 10:17:23 UTC
import datetime

version = "1.5.0"
githash = "9492e4e252ea07c137272aea02ee5ef0e838a415"


major = 1
minor = 5
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 4, 2, 10, 17, 23)
debug = False

astropy_helpers_version = "3.2.2"
