# This is a basic workflow to help you get started with Actions
name: Dependency Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # The matrix of python versions to run
    strategy:
        matrix:
            os: [ubuntu-20.04, windows-latest]
            python-version: ['3.7','3.8','3.9']   
            #If adjusted here, make sure to also adjust the bindings in tox.ini

    # The steps to run for each python version
    steps:
        # Checks out the repository
        - uses: actions/checkout@v2
        # Setups the required python version
        - name: Setup python ${{  matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        # Installs tox and tox-gh-actions to run tox testing
        - name: Install dependencies
          run:  |
            python -m pip install --upgrade pip
            python -m pip install tox tox-gh-actions
        # Run tests with tox (tests multiple subpackages)
        - name: Run tests with tox
          run: tox
